
name = "Workload"
description = "Computes the workload of a resource at event occurence."
classification = ["environmental"]

[[variant]]
  name = "Eventsum"
  description = "Sums up the number of events associated with the resource for the last x (default 12) hours."

  quality = 7

  [variant.requirements]
    attribute_keys = []

  [[variant.configuration]]
    key = "time_window"
    name = "Time window"
    description = "Timewindow that should be used to compute the workload"
    required = false
    default = "12h"

[[variant]]
  name = "Open Cases"
  description = "Calculated the number of open but not completed cases at a given point in time."

  quality = 7

  [variant.requirements]
    attribute_keys = []
