
name = "Processing Speed"
description = "Computes the processing speed of a resource."

[[variant]]
  name = "Service Time"
  description = "For each \"complete\" event of the resource, the timespan to the \"start\" event is calculated."

  quality = 7

  [variant.requirements]
    attribute_keys = []
